[db]
postgres = "postgresql://postgres:postgres@127.0.0.1:5432/cic_dw"
redis    = "redis://127.0.0.1:6379/0"

[server]
address = ":3000"
cors = [
    "https://dashboard.sarafu.network",
    "https://dashboard.grassecon.org",
    "https://dashboard.grassrootseconomics.org",
    "http://localhost:3000"
]

[chain]
index = "0x5A1EB529438D8b3cA943A45a48744f4c73d1f098"
balances_resolver = "0x9C48FF0888A747Ba0108E7205Cae2EeB0C76c948"
rpc   = "http://127.0.0.1:8545"

[syncers]
cache = "@every 20s"
ussd  = "@every 30s"
token = "@every 1m"