[db]
postgres = "postgresql://postgres:postgres@127.0.0.1:5432/cic_dw"
redis    = "redis://127.0.0.1:6379/0"

[server]
address = ":3000"
cors = [
    "https://dashboard.sarafu.network",
    "https://dashboard.grassecon.org",
    "https://dashboard.grassrootseconomics.org",
    "http://localhost:3000"
]

[chain]
index = "0x885190Daf52F011B7F6954a255ef5247b04ff70f"
balances_resolver = "0xb9e215B789e9Ec6643Ba4ff7b98EA219F38c6fE5"
rpc   = "http://127.0.0.1:8545"

[syncer]
enabled = true

[api]
enabled = true

[syncers]
cache = "@every 20s"
ussd  = "@every 30s"
token = "@every 1m"

[meta]
endpoint = "http://cic-meta-server:8000"

[jwt]
secret = "0xd34db33f"