services:
  postgres:
    image: postgres:14-alpine
    restart: unless-stopped
    network_mode: "host"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=cic_dw
    volumes:
      - cic-dw-db:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  redis:
    image: redis:6-alpine
    restart: unless-stopped
    network_mode: "host"
    command: redis-server --loglevel warning
    ports:
      - '6379:6379'

volumes:
  cic-dw-db:
    driver: local
