name: goreleaser

on:
  push:
    tags:
      - "v*"

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    environment: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Login to Docker Registry
        uses: docker/login-action@v1
        with:
          registry: docker.grassecon.net
          username: ${{ secrets.GEDOCKER_USERNAME }}
          password: ${{ secrets.GEDOCKER_PASSWORD }}

      - name: Prepare Dependencies
        run: |
          make dist
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: --parallelism 1 --rm-dist --skip-validate
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
